name: Daily Log Commit

on:
  schedule:
    # Scheduled to run every day at 9:40 AM UTC
    - cron: '40 9 * * *'
  workflow_dispatch:
    # Allows manual trigger

jobs:
  check-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Count commits for today
      id: count_commits
      run: |
        today=$(date +"%Y-%m-%d")
        commit_count=$(git log --since="$today 00:00" --until="$today 23:59" --pretty=oneline | wc -l)
        echo "commit_count=$commit_count" >> $GITHUB_ENV

    - name: Create a log file if commits are less than 10
      if: ${{ env.commit_count && fromJson(env.commit_count) < 10 }}
      run: |
        date=$(date +"%Y-%m-%d")
        mkdir -p logs
        echo "Log created on $date" > logs/log_$date.txt
        git add logs/log_$date.txt
        git commit -m "Add log file for $date"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        git push
