name: Daily Log Commit

on:
  schedule:
    - cron: '30 17 * * *'  # 11:00 PM IST
  workflow_dispatch:

jobs:
  check-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Git with your identity
      run: |
        git config user.name "themysterysolver"
        git config user.email "arjunprabhakar1910@gmail.com"

    - name: Count commits for today
      id: count_commits
      run: |
        today=$(date +"%Y-%m-%d")
        commit_count=$(git log --since="$today 00:00" --until="$today 23:59" --pretty=oneline | wc -l)
        echo "commit_count=$commit_count" >> $GITHUB_ENV

    - name: Create a log file if commits are less than 5
      if: ${{ env.commit_count && fromJson(env.commit_count) < 5 }}
      run: |
        date=$(date +"%Y-%m-%d")
        mkdir -p logs
        echo "Log created on $date at $(date +%H:%M:%S)" > logs/log_$date.txt
        git add logs/log_$date.txt
        git commit -m "Add log file for $date"
        git remote set-url origin https://x-access-token:${{ secrets.MY_PERSONAL_TOKEN }}@github.com/${{ github.repository }}.git
        git push